#!/usr/bin/env bash
# End-to-end validation of a deployed stack. Read-only against your own data
# except for one seeded test certificate, which it deletes again at the end.
#
# Answers the question "is this thing actually working?" by exercising the real
# path the browser uses: Cognito sign-in -> ID token -> API Gateway (with the
# Cognito authorizer) -> Lambda -> DynamoDB, plus the CORS preflight.
#
# Usage:  ./scripts/validate.sh            (needs outputs.json from ./deploy.sh)
# Exits non-zero on the first failed check.
set -euo pipefail

cd "$(dirname "$0")/.."

REGION="ap-southeast-1"
TEST_EMAIL="${TEST_EMAIL:-crm-validate@example.com}"
TEST_PASSWORD="${TEST_PASSWORD:-ValidateCrm123!}"
CERT_TABLE="app-d9fae51c-1929cc69-cert-inventory"
SEEDED_CERT_ID="validate-smoke-test-cert"

pass() { printf '  \033[32mPASS\033[0m  %s\n' "$1"; }
fail() { printf '  \033[31mFAIL\033[0m  %s\n' "$1" >&2; exit 1; }
step() { printf '\n\033[1m%s\033[0m\n' "$1"; }

# Resolves API_URL / APP_URL / USER_POOL_ID / USER_POOL_CLIENT_ID from
# outputs.json when present, and from CloudFormation when it is not — which is
# the normal case, since this project deploys on push and outputs.json is
# gitignored, so ./deploy.sh never runs on your machine.
# shellcheck source=scripts/lib-stack-outputs.sh
source scripts/lib-stack-outputs.sh
CLIENT_ID="$USER_POOL_CLIENT_ID"

step "1. Static site is served"
UI_STATUS="$(curl -s -o /dev/null -w '%{http_code}' "$APP_URL/")"
[ "$UI_STATUS" = "200" ] || fail "GET $APP_URL/ returned $UI_STATUS (expected 200)"
pass "$APP_URL/ -> 200"

curl -s "$APP_URL/config.js" | grep -q "userPoolId" \
  || fail "config.js at $APP_URL is missing userPoolId — deploy.sh did not write it"
pass "config.js is present and populated"

step "2. CORS preflight (the OPTIONS request the browser sends first)"
# A preflight carries NO Authorization header. It must still return 2xx with an
# Access-Control-Allow-Origin header, or the browser blocks the real request.
PREFLIGHT="$(curl -s -i -X OPTIONS "$API_URL/certs" \
  -H "Origin: $APP_URL" \
  -H "Access-Control-Request-Method: GET" \
  -H "Access-Control-Request-Headers: authorization,content-type")"

PREFLIGHT_STATUS="$(printf '%s' "$PREFLIGHT" | head -n1 | awk '{print $2}')"
case "$PREFLIGHT_STATUS" in
  2*) pass "OPTIONS /certs -> $PREFLIGHT_STATUS" ;;
  403) fail "OPTIONS /certs -> 403: no OPTIONS method exists (Cors missing from CrmApi)" ;;
  401) fail "OPTIONS /certs -> 401: the authorizer is on the preflight (set AddDefaultAuthorizerToCorsPreflight: false)" ;;
  *)   fail "OPTIONS /certs -> $PREFLIGHT_STATUS" ;;
esac

printf '%s' "$PREFLIGHT" | grep -qi "access-control-allow-origin" \
  || fail "preflight response has no Access-Control-Allow-Origin header"
pass "preflight returns Access-Control-Allow-Origin"

step "3. The API rejects unauthenticated calls"
ANON_STATUS="$(curl -s -o /dev/null -w '%{http_code}' "$API_URL/certs")"
[ "$ANON_STATUS" = "401" ] || fail "GET /certs with no token returned $ANON_STATUS (expected 401)"
pass "GET /certs without a token -> 401"

# An authorizer 401 is generated by API Gateway, not the Lambda, so only a
# GatewayResponse can put CORS headers on it. Without them the browser shows an
# opaque CORS error instead of the real 401.
curl -s -i "$API_URL/certs" -H "Origin: $APP_URL" | grep -qi "access-control-allow-origin" \
  || fail "the 401 carries no Access-Control-Allow-Origin (GatewayResponse missing)"
pass "the 401 still carries CORS headers (readable in a browser)"

step "4. Test user in Cognito"
if aws cognito-idp admin-get-user --user-pool-id "$USER_POOL_ID" \
     --username "$TEST_EMAIL" --region "$REGION" >/dev/null 2>&1; then
  pass "test user $TEST_EMAIL already exists"
else
  aws cognito-idp admin-create-user --user-pool-id "$USER_POOL_ID" \
    --username "$TEST_EMAIL" --message-action SUPPRESS \
    --user-attributes Name=email,Value="$TEST_EMAIL" Name=email_verified,Value=true \
    --region "$REGION" >/dev/null
  pass "created test user $TEST_EMAIL"
fi

aws cognito-idp admin-set-user-password --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_EMAIL" --password "$TEST_PASSWORD" --permanent --region "$REGION"
pass "password set (permanent, no FORCE_CHANGE_PASSWORD challenge)"

USER_SUB="$(aws cognito-idp admin-get-user --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_EMAIL" --region "$REGION" \
  --query "UserAttributes[?Name=='sub'].Value | [0]" --output text)"
pass "user sub = $USER_SUB"

step "5. Sign in and get an ID token"
ID_TOKEN="$(aws cognito-idp admin-initiate-auth \
  --user-pool-id "$USER_POOL_ID" --client-id "$CLIENT_ID" \
  --auth-flow ADMIN_USER_PASSWORD_AUTH \
  --auth-parameters USERNAME="$TEST_EMAIL",PASSWORD="$TEST_PASSWORD" \
  --region "$REGION" --query 'AuthenticationResult.IdToken' --output text)"
[ -n "$ID_TOKEN" ] && [ "$ID_TOKEN" != "None" ] || fail "no ID token returned"
pass "got an ID token"

step "6. Authenticated API calls"
# The empty-list case is itself a meaningful result: it proves the authorizer
# accepted the token, the Lambda ran, and the DynamoDB query succeeded.
for path in /certs /iam/accounts; do
  BODY="$(curl -s -w '\n%{http_code}' "$API_URL$path" -H "Authorization: $ID_TOKEN")"
  STATUS="$(printf '%s' "$BODY" | tail -n1)"
  JSON="$(printf '%s' "$BODY" | sed '$d')"
  [ "$STATUS" = "200" ] || fail "GET $path -> $STATUS: $JSON"
  printf '%s' "$JSON" | jq -e 'has("items")' >/dev/null \
    || fail "GET $path did not return an items array: $JSON"
  pass "GET $path -> 200, $(printf '%s' "$JSON" | jq '.items | length') item(s)"
done

# /audit requires entityId; a non-admin may only query their own actor id.
AUDIT_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/audit?entityId=$USER_SUB" -H "Authorization: $ID_TOKEN")"
[ "$AUDIT_STATUS" = "200" ] || fail "GET /audit?entityId=<own sub> -> $AUDIT_STATUS (expected 200)"
pass "GET /audit?entityId=<own sub> -> 200"

MISSING_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/audit" -H "Authorization: $ID_TOKEN")"
[ "$MISSING_STATUS" = "400" ] || fail "GET /audit with no entityId -> $MISSING_STATUS (expected 400)"
pass "GET /audit without entityId -> 400"

FORBIDDEN_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/audit?entityId=someone-elses-id" -H "Authorization: $ID_TOKEN")"
[ "$FORBIDDEN_STATUS" = "403" ] || fail "cross-owner /audit -> $FORBIDDEN_STATUS (expected 403)"
pass "cross-owner /audit as a non-admin -> 403 (owner scoping enforced)"

step "7. Seed a certificate owned by this user, then read it back"
# GET /certs reads the shared team partition PLUS the caller's own sub, so a row
# owned by this login is still returned — that backwards compatibility is what
# this step checks. The shared partition is checked separately in step 7b.
EXPIRY="$(python3 -c "
import datetime
print((datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=10)).date().isoformat())
")"

aws dynamodb put-item --table-name "$CERT_TABLE" --region "$REGION" --item "$(cat <<EOF
{
  "CertId":     {"S": "$SEEDED_CERT_ID"},
  "OwnerId":    {"S": "$USER_SUB"},
  "CertType":   {"S": "ACM"},
  "Domain":     {"S": "validate.example.com"},
  "ExpiryDate": {"S": "$EXPIRY"},
  "Status":     {"S": "ISSUED"},
  "Source":     {"S": "validate.sh"}
}
EOF
)"
pass "seeded $SEEDED_CERT_ID (OwnerId = $USER_SUB, expires $EXPIRY)"

SEEDED_JSON="$(curl -s "$API_URL/certs" -H "Authorization: $ID_TOKEN")"
printf '%s' "$SEEDED_JSON" | jq -e --arg id "$SEEDED_CERT_ID" \
  '.items | map(.CertId) | index($id) != null' >/dev/null \
  || fail "seeded cert not returned by GET /certs: $SEEDED_JSON"
pass "GET /certs returns the seeded cert (owner scoping + GSI query work)"

step "7b. The shared team inventory is visible to this login"
# The bug this proves fixed: OwnerId is OwnerIndex's HASH key, so querying it with
# the caller's Cognito sub alone made every row belong to exactly one login —
# members of one team saw different dashboards, and every row written by discovery
# (owned by a service identity, never a sub) appeared in nobody's.
SHARED_OWNER_ID="crm-resource-owners"
SHARED_COUNT="$(printf '%s' "$SEEDED_JSON" | jq --arg owner "$SHARED_OWNER_ID" \
  '[.items[] | select(.OwnerId == $owner)] | length')"
[ "${SHARED_COUNT:-0}" -gt 0 ] \
  || fail "GET /certs returned no rows owned by $SHARED_OWNER_ID — this login cannot
       see the shared team inventory, which is the per-login isolation bug.
       Check that ./deploy.sh seeded it and that SHARED_OWNER_ID agrees across
       crm_common, template.yaml and gen_demo_data.py."
pass "GET /certs returns $SHARED_COUNT row(s) from the shared partition (every login sees them)"

# Every status must agree with its own expiry date. A row reading ISSUED that
# expired months ago is the "the data makes no sense" report.
INCONSISTENT="$(printf '%s' "$SEEDED_JSON" | jq -r --arg today "$(date -u +%F)" \
  '[.items[] | select((.ExpiryDate[0:10] < $today and .Status == "ISSUED")
                   or (.ExpiryDate[0:10] > $today and .Status == "EXPIRED"))
    | .CertId] | join(", ")')"
[ -z "$INCONSISTENT" ] \
  || fail "these rows carry a Status that contradicts their ExpiryDate: $INCONSISTENT"
pass "every row's Status agrees with its ExpiryDate"

DETAIL_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/certs/$SEEDED_CERT_ID" -H "Authorization: $ID_TOKEN")"
[ "$DETAIL_STATUS" = "200" ] || fail "GET /certs/$SEEDED_CERT_ID -> $DETAIL_STATUS"
pass "GET /certs/$SEEDED_CERT_ID -> 200"

step "8. Renew the seeded cert (the full async path)"
# This is the check that would have caught the boundary-denied ACM call: the POST
# returns 202 whether or not the state machine can actually do the work, so the
# only honest test is to poll the execution to a terminal state.
RENEW_JSON="$(curl -s -X POST "$API_URL/certs/$SEEDED_CERT_ID/renew" \
  -H "Authorization: $ID_TOKEN")"

EXECUTION_ARN="$(printf '%s' "$RENEW_JSON" | jq -r '.executionArn // empty')"
[ -n "$EXECUTION_ARN" ] \
  || fail "POST /certs/$SEEDED_CERT_ID/renew returned no executionArn: $RENEW_JSON
       A \"Step Functions call failed\" error here names the denied action."
pass "POST /certs/$SEEDED_CERT_ID/renew -> 202 ($EXECUTION_ARN)"

# Percent-encode the ARN exactly as the browser's encodeURIComponent does. This
# matters: an execution ARN is full of colons, and curl will happily send them
# raw (which API Gateway delivers decoded) while the browser cannot. Testing the
# raw form passed here while every poll in the browser failed with
# `InvalidArn: Invalid ARN prefix: arn%3Aaws%3A...`.
ENCODED_ARN="$(printf '%s' "$EXECUTION_ARN" | jq -sRr @uri)"

# The renewal state machine settles in a couple of seconds; poll rather than sleep.
EXECUTION_STATUS="RUNNING"
for _ in $(seq 1 20); do
  sleep 2
  EXECUTION_JSON="$(curl -s "$API_URL/executions/$ENCODED_ARN" -H "Authorization: $ID_TOKEN")"
  EXECUTION_STATUS="$(printf '%s' "$EXECUTION_JSON" | jq -r '.status // "UNKNOWN"')"
  [ "$EXECUTION_STATUS" = "RUNNING" ] || break
done

case "$EXECUTION_STATUS" in
  SUCCEEDED) pass "renewal execution SUCCEEDED" ;;
  RUNNING)   fail "renewal execution still RUNNING after 40s: $EXECUTION_ARN" ;;
  *)         fail "renewal execution $EXECUTION_STATUS — the renew button will
       silently do nothing. Inspect the failing state:
         aws stepfunctions get-execution-history --execution-arn $EXECUTION_ARN \\
           --region $REGION --reverse-order --max-items 10
       Response was: $EXECUTION_JSON" ;;
esac

# Renewal writes a new ExpiryDate; if the row did not move, the executor ran but
# wrote nothing — a silent success that looks identical to a working renewal.
RENEWED_EXPIRY="$(curl -s "$API_URL/certs/$SEEDED_CERT_ID" -H "Authorization: $ID_TOKEN" \
  | jq -r '.ExpiryDate // empty')"
[ -n "$RENEWED_EXPIRY" ] && [ "$RENEWED_EXPIRY" != "$EXPIRY" ] \
  || fail "ExpiryDate is still $EXPIRY after a SUCCEEDED renewal — the executor
       reported success without writing to cert-inventory"
pass "ExpiryDate moved $EXPIRY -> $RENEWED_EXPIRY"

step "9. Clean up"
aws dynamodb delete-item --table-name "$CERT_TABLE" --region "$REGION" \
  --key "{\"CertId\": {\"S\": \"$SEEDED_CERT_ID\"}}"
pass "removed $SEEDED_CERT_ID"

cat <<EOF

$(printf '\033[32mAll checks passed.\033[0m')

The API, Cognito authorizer, CORS and DynamoDB access all work end to end.

To see it in the browser, open $APP_URL and sign in as:
  email:    $TEST_EMAIL
  password: $TEST_PASSWORD

The Certificates tab shows whatever rows carry your own Cognito sub as OwnerId.
Discovery derives OwnerId from an IAM path or a resource tag, not from a Cognito
sub, so genuinely discovered rows appear in nobody's UI — an empty tab is the
normal state on a fresh login, not a fault. deploy.sh seeds demo rows against
SEED_OWNER_ID; set it to your own sub and redeploy, or re-run this script's step
7 by hand, to make rows appear for your login.
EOF
