#!/usr/bin/env bash
# End-to-end validation of a deployed stack. Read-only against your own data
# except for one seeded test certificate, which it deletes again at the end.
#
# Answers the question "is this thing actually working?" by exercising the real
# path the browser uses: Cognito sign-in -> ID token -> API Gateway (with the
# Cognito authorizer) -> Lambda -> DynamoDB, plus the CORS preflight.
#
# Usage:  ./scripts/validate.sh            (needs outputs.json from ./deploy.sh)
# Exits non-zero on the first failed check.
set -euo pipefail

cd "$(dirname "$0")/.."

REGION="ap-southeast-1"
TEST_EMAIL="${TEST_EMAIL:-crm-validate@example.com}"
TEST_PASSWORD="${TEST_PASSWORD:-ValidateCrm123!}"
CERT_TABLE="app-d9fae51c-1929cc69-cert-inventory"
SEEDED_CERT_ID="validate-smoke-test-cert"

pass() { printf '  \033[32mPASS\033[0m  %s\n' "$1"; }
fail() { printf '  \033[31mFAIL\033[0m  %s\n' "$1" >&2; exit 1; }
step() { printf '\n\033[1m%s\033[0m\n' "$1"; }

# Resolves API_URL / APP_URL / USER_POOL_ID / USER_POOL_CLIENT_ID from
# outputs.json when present, and from CloudFormation when it is not — which is
# the normal case, since this project deploys on push and outputs.json is
# gitignored, so ./deploy.sh never runs on your machine.
# shellcheck source=scripts/lib-stack-outputs.sh
source scripts/lib-stack-outputs.sh
CLIENT_ID="$USER_POOL_CLIENT_ID"

step "1. Static site is served"
UI_STATUS="$(curl -s -o /dev/null -w '%{http_code}' "$APP_URL/")"
[ "$UI_STATUS" = "200" ] || fail "GET $APP_URL/ returned $UI_STATUS (expected 200)"
pass "$APP_URL/ -> 200"

curl -s "$APP_URL/config.js" | grep -q "userPoolId" \
  || fail "config.js at $APP_URL is missing userPoolId — deploy.sh did not write it"
pass "config.js is present and populated"

step "2. CORS preflight (the OPTIONS request the browser sends first)"
# A preflight carries NO Authorization header. It must still return 2xx with an
# Access-Control-Allow-Origin header, or the browser blocks the real request.
PREFLIGHT="$(curl -s -i -X OPTIONS "$API_URL/certs" \
  -H "Origin: $APP_URL" \
  -H "Access-Control-Request-Method: GET" \
  -H "Access-Control-Request-Headers: authorization,content-type")"

PREFLIGHT_STATUS="$(printf '%s' "$PREFLIGHT" | head -n1 | awk '{print $2}')"
case "$PREFLIGHT_STATUS" in
  2*) pass "OPTIONS /certs -> $PREFLIGHT_STATUS" ;;
  403) fail "OPTIONS /certs -> 403: no OPTIONS method exists (Cors missing from CrmApi)" ;;
  401) fail "OPTIONS /certs -> 401: the authorizer is on the preflight (set AddDefaultAuthorizerToCorsPreflight: false)" ;;
  *)   fail "OPTIONS /certs -> $PREFLIGHT_STATUS" ;;
esac

printf '%s' "$PREFLIGHT" | grep -qi "access-control-allow-origin" \
  || fail "preflight response has no Access-Control-Allow-Origin header"
pass "preflight returns Access-Control-Allow-Origin"

step "3. The API rejects unauthenticated calls"
ANON_STATUS="$(curl -s -o /dev/null -w '%{http_code}' "$API_URL/certs")"
[ "$ANON_STATUS" = "401" ] || fail "GET /certs with no token returned $ANON_STATUS (expected 401)"
pass "GET /certs without a token -> 401"

# An authorizer 401 is generated by API Gateway, not the Lambda, so only a
# GatewayResponse can put CORS headers on it. Without them the browser shows an
# opaque CORS error instead of the real 401.
curl -s -i "$API_URL/certs" -H "Origin: $APP_URL" | grep -qi "access-control-allow-origin" \
  || fail "the 401 carries no Access-Control-Allow-Origin (GatewayResponse missing)"
pass "the 401 still carries CORS headers (readable in a browser)"

step "4. Test user in Cognito"
if aws cognito-idp admin-get-user --user-pool-id "$USER_POOL_ID" \
     --username "$TEST_EMAIL" --region "$REGION" >/dev/null 2>&1; then
  pass "test user $TEST_EMAIL already exists"
else
  aws cognito-idp admin-create-user --user-pool-id "$USER_POOL_ID" \
    --username "$TEST_EMAIL" --message-action SUPPRESS \
    --user-attributes Name=email,Value="$TEST_EMAIL" Name=email_verified,Value=true \
    --region "$REGION" >/dev/null
  pass "created test user $TEST_EMAIL"
fi

aws cognito-idp admin-set-user-password --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_EMAIL" --password "$TEST_PASSWORD" --permanent --region "$REGION"
pass "password set (permanent, no FORCE_CHANGE_PASSWORD challenge)"

USER_SUB="$(aws cognito-idp admin-get-user --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_EMAIL" --region "$REGION" \
  --query "UserAttributes[?Name=='sub'].Value | [0]" --output text)"
pass "user sub = $USER_SUB"

step "5. Sign in and get an ID token"
ID_TOKEN="$(aws cognito-idp admin-initiate-auth \
  --user-pool-id "$USER_POOL_ID" --client-id "$CLIENT_ID" \
  --auth-flow ADMIN_USER_PASSWORD_AUTH \
  --auth-parameters USERNAME="$TEST_EMAIL",PASSWORD="$TEST_PASSWORD" \
  --region "$REGION" --query 'AuthenticationResult.IdToken' --output text)"
[ -n "$ID_TOKEN" ] && [ "$ID_TOKEN" != "None" ] || fail "no ID token returned"
pass "got an ID token"

step "6. Authenticated API calls"
# The empty-list case is itself a meaningful result: it proves the authorizer
# accepted the token, the Lambda ran, and the DynamoDB query succeeded.
for path in /certs /ad-accounts; do
  BODY="$(curl -s -w '\n%{http_code}' "$API_URL$path" -H "Authorization: $ID_TOKEN")"
  STATUS="$(printf '%s' "$BODY" | tail -n1)"
  JSON="$(printf '%s' "$BODY" | sed '$d')"
  [ "$STATUS" = "200" ] || fail "GET $path -> $STATUS: $JSON"
  printf '%s' "$JSON" | jq -e 'has("items")' >/dev/null \
    || fail "GET $path did not return an items array: $JSON"
  pass "GET $path -> 200, $(printf '%s' "$JSON" | jq '.items | length') item(s)"
done

# /audit requires entityId; a non-admin may only query their own actor id.
AUDIT_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/audit?entityId=$USER_SUB" -H "Authorization: $ID_TOKEN")"
[ "$AUDIT_STATUS" = "200" ] || fail "GET /audit?entityId=<own sub> -> $AUDIT_STATUS (expected 200)"
pass "GET /audit?entityId=<own sub> -> 200"

MISSING_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/audit" -H "Authorization: $ID_TOKEN")"
[ "$MISSING_STATUS" = "400" ] || fail "GET /audit with no entityId -> $MISSING_STATUS (expected 400)"
pass "GET /audit without entityId -> 400"

FORBIDDEN_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/audit?entityId=someone-elses-id" -H "Authorization: $ID_TOKEN")"
[ "$FORBIDDEN_STATUS" = "403" ] || fail "cross-owner /audit -> $FORBIDDEN_STATUS (expected 403)"
pass "cross-owner /audit as a non-admin -> 403 (owner scoping enforced)"

step "7. Seed a certificate owned by this user, then read it back"
# Nothing appears in the UI unless OwnerId equals your Cognito sub: the API
# queries OwnerIndex on the sub, while discovery derives OwnerId from an ACM
# domain name / IAM cert path / the crm:owner-id tag. This is why a correctly
# working deployment still shows "No certificates found" on a fresh account.
EXPIRY="$(python3 -c "
import datetime
print((datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=10)).date().isoformat())
")"

aws dynamodb put-item --table-name "$CERT_TABLE" --region "$REGION" --item "$(cat <<EOF
{
  "CertId":     {"S": "$SEEDED_CERT_ID"},
  "OwnerId":    {"S": "$USER_SUB"},
  "CertType":   {"S": "ACM"},
  "Domain":     {"S": "validate.example.com"},
  "ExpiryDate": {"S": "$EXPIRY"},
  "Status":     {"S": "ACTIVE"},
  "Source":     {"S": "validate.sh"}
}
EOF
)"
pass "seeded $SEEDED_CERT_ID (OwnerId = $USER_SUB, expires $EXPIRY)"

SEEDED_JSON="$(curl -s "$API_URL/certs" -H "Authorization: $ID_TOKEN")"
printf '%s' "$SEEDED_JSON" | jq -e --arg id "$SEEDED_CERT_ID" \
  '.items | map(.CertId) | index($id) != null' >/dev/null \
  || fail "seeded cert not returned by GET /certs: $SEEDED_JSON"
pass "GET /certs returns the seeded cert (owner scoping + GSI query work)"

DETAIL_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
  "$API_URL/certs/$SEEDED_CERT_ID" -H "Authorization: $ID_TOKEN")"
[ "$DETAIL_STATUS" = "200" ] || fail "GET /certs/$SEEDED_CERT_ID -> $DETAIL_STATUS"
pass "GET /certs/$SEEDED_CERT_ID -> 200"

step "8. Clean up"
aws dynamodb delete-item --table-name "$CERT_TABLE" --region "$REGION" \
  --key "{\"CertId\": {\"S\": \"$SEEDED_CERT_ID\"}}"
pass "removed $SEEDED_CERT_ID"

cat <<EOF

$(printf '\033[32mAll checks passed.\033[0m')

The API, Cognito authorizer, CORS and DynamoDB access all work end to end.

To see it in the browser, open $APP_URL and sign in as:
  email:    $TEST_EMAIL
  password: $TEST_PASSWORD

The Certificates tab will be empty — that is correct on a fresh account. Re-run
this script's step 7 (or seed your own row) with OwnerId set to your own
Cognito sub to make rows appear for your own login.
EOF
